### ISSUE TITLE
ut crashes while parsing timestamp in milliseconds

### ISSUE THREAD

**Issue by mardukbp** [yoshihitoh/ut-cli#50]
I installed `ut` on Windows 10 with `cargo`. Then I executed

`ut -p ms g`

Then I fed the result to `ut p` and got the following output:

````
thread 'main' panicked at 'SystemTimeToFileTime failed with: Wrong Parameter. (os error 87)',
C:\Users\marduk\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.42\src\sys.rs:851:13
````

**Comment by ghost** [comment]
`ut p` does not recognize the precision of timestamps, so I think `ut -p ms p` will solve this.

Maybe this behavior depending on the running platform. Below is a result on macos.
```
$ ut -p ms g | ut p
+52242-07-30 04:02:03 (+09:00)
```

I'll check this issue in the coming weekend.

**Comment by mardukbp** [comment]
I just tried `ut -p ms g | ut p` on Windows 10 using the pre-built binaries you just uploaded and ut crashed with:

```
thread 'main' panicked at 'SystemTimeToFileTime failed with: Wrong Parameter. (os error 87)', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\time-0.1.42\src\sys.rs:851:13
```

Setting `RUST_BACKTRACE=full`, the backtrace for the MSVC build is:

```
stack backtrace:
   0:     0x7ff6e288ce8f - <unknown>
   1:     0x7ff6e289e20b - <unknown>
   2:     0x7ff6e288a46c - <unknown>
   3:     0x7ff6e288fecc - <unknown>
   4:     0x7ff6e288fb0f - <unknown>
   5:     0x7ff6e28906b7 - <unknown>
   6:     0x7ff6e289023f - <unknown>
   7:     0x7ff6e28901ac - <unknown>
   8:     0x7ff6e282a0db - <unknown>
   9:     0x7ff6e2829bdf - <unknown>
  10:     0x7ff6e2828ebb - <unknown>
  11:     0x7ff6e277e795 - <unknown>
  12:     0x7ff6e27741d8 - <unknown>
  13:     0x7ff6e27780ad - <unknown>
  14:     0x7ff6e2773d76 - <unknown>
  15:     0x7ff6e28908ca - <unknown>
  16:     0x7ff6e2778717 - <unknown>
  17:     0x7ff6e28a48a0 - <unknown>
  18:     0x7ffb588b7bd4 - BaseThreadInitThunk
  19:     0x7ffb59dcced1 - RtlUserThreadStart
```

For the GNU build the backtrace is:

```
stack backtrace:
   0:           0x5da9db - backtrace::backtrace::dbghelp::trace::h378ea4cbe85ad19b
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1:           0x5da9db - backtrace::backtrace::trace_unsynchronized::h17ecd00cea9f5cec
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2:           0x5da9db - std::sys_common::backtrace::_print_fmt::h90aab22c78b468f9
                               at src\libstd\sys_common/backtrace.rs:78
   3:           0x5da9db - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb09a5e22c3c55523
                               at src\libstd\sys_common/backtrace.rs:59
   4:           0x606a7b - core::fmt::write::h544682cacecab87f
                               at src\libcore\fmt/mod.rs:1069
   5:           0x5cb755 - std::io::Write::write_fmt::h634643c14d006ed6
                               at src\libstd\io/mod.rs:1504
   6:           0x5df221 - std::sys_common::backtrace::_print::h8faf3aaf87a761c8
                               at src\libstd\sys_common/backtrace.rs:62
   7:           0x5df221 - std::sys_common::backtrace::print::h8688c9b14176cc3f
                               at src\libstd\sys_common/backtrace.rs:49
   8:           0x5df221 - std::panicking::default_hook::{{closure}}::heb6abe2007251ee5
                               at src\libstd/panicking.rs:198
   9:           0x5dee96 - std::panicking::default_hook::h91ea2fa0a70cfce4
                               at src\libstd/panicking.rs:218
  10:           0x5df894 - std::panicking::rust_panic_with_hook::h59b303d092c2cdfe
                               at src\libstd/panicking.rs:511
  11:           0x5df4b4 - rust_begin_unwind
                               at src\libstd/panicking.rs:419
  12:           0x5df42c - std::panicking::begin_panic_fmt::hda684017d1ad5cf0
                               at src\libstd/panicking.rs:373
  13:           0x529983 - time::sys::inner::utc_tm_to_time::h92f1884dcc95b763
  14:           0x52741f - time::Tm::to_timespec::h852e6088e22b3f10
  15:           0x517f2a - <chrono::offset::local::Local as chrono::offset::TimeZone>::from_utc_datetime::he4c77b9e72f99f90
  16:           0x412115 - ut::precision::Precision::parse_timestamp::hd059c4f259a0e8c8
  17:           0x405ff1 - ut::cmd::parse::run::run::h510a8ace9aa01eeb
  18:           0x40a736 - ut::main::h0807f5590c5dabbd
  19:           0x405536 - std::rt::lang_start::{{closure}}::hce5f0479c8e6970e
  20:           0x5dfb70 - std::rt::lang_start_internal::{{closure}}::h38e97fd6510ec4d9
                               at src\libstd/rt.rs:52
  21:           0x5dfb70 - std::panicking::try::do_call::h039952da422b7d65
                               at src\libstd/panicking.rs:331
  22:           0x5dfb70 - std::panicking::try::hbdfe38dea5ddc65e
                               at src\libstd/panicking.rs:274
  23:           0x5dfb70 - std::panic::catch_unwind::h2b6fbcc27f8dd3ee
                               at src\libstd/panic.rs:394
  24:           0x5dfb70 - std::rt::lang_start_internal::he75132b3f567b7bf
                               at src\libstd/rt.rs:51
  25:           0x40ab28 - main
  26:           0x4013c7 - _tmainCRTStartup
  27:           0x4014fb - mainCRTStartup
  28:     0x7ffb588b7bd4 - _report_error
  29:     0x7ffb59dcced1 - _report_error
```

**Comment by yoshihitoh** [comment]
Sorry for the late reply, and thank you for the detail!

I think `ut -p ms g | ut -p ms p` will work. (Add `-p ms` on `ut p` command.)

On the windows platform, `time` module uses Windows API `SystemTimeToFileTime` which accepts a year range 1601 to 30827, so that ut crashes on `ut p`. 

``` bash
$ ut -p ms g | ut -p ms p
2020-04-21 15:22:18.893 (+09:00)   # ok

$ ut -p ms g | ut p
+52274-04-17 22:05:33 (+09:00)   # ng. 52274 is greater than 30827
```

ref:
- https://docs.microsoft.com/ja-jp/windows/win32/api/timezoneapi/nf-timezoneapi-systemtimetofiletime
- https://docs.microsoft.com/ja-jp/windows/win32/api/minwinbase/ns-minwinbase-systemtime

I'm planning to add a limitation on the timestamp range, allow the year from 1900 to 2999.

**Comment by mardukbp** [comment]
`ut -p ms g | ut -p ms p` works indeed on Windows 10. Thank you so much for the explanation and thank you again for writing this program!

**Comment by yoshihitoh** [comment]
@mardukbp  Thank you for reporting the result!

>  thank you again for writing this program!

I'm really glad to hear this :)

If you usually use timestamps in milliseconds, you can use environment variable `UT_PRECISION`like below.

```batch
# this is the equivalent to the `-p ms` option.
$ set UT_PRECISION=ms

# generate a timestamp in milliseconds.
$ ut g
1587999352279

# parse timestamp in milliseconds.
$ echo 1587999352279 | ut p
2020-04-27 23:55:52.279 (+09:00)
```

**Comment by mardukbp** [comment]
Great! That is a time-saver
